### ISSUE TITLE
0 ttl for LRU cache

### ISSUE THREAD

**Issue by cmfatih** [hapijs/catbox#123]
Is there any way to use 0 ttl? I use memcached and it treats the value as a Unix timestamp IF the value is greater than `2592000`. ( https://github.com/memcached/memcached/blob/master/doc/protocol.txt#L79 )  Basically I want to use 0 ttl in memcached which means no expire until memory is full. When memory is full then eviction will start.

P.S. : I can easily change [the mamcached engine](https://www.npmjs.com/package/catbox-memcached2) if I can solve this issue at engine level... But I couldn't found a solution other than catbox itself.

Update: Actually I think I can handle memcached's special case. I can convert timestamp to ttl before send it back from engine to catbox's client call. But it would be nice `to use catbox as a generic storage adapter`.

**Comment by hueniverse** [comment]
Hmm. You are basically asking for storage instead of caching (the fact that the storage provider is going to act as a cache is beside the point). I have resisted this in the past but the need did come up.

Anyone else looking to use catbox as a generic storage adapter, not just caching?

**Comment by hueniverse** [comment]
I think the right approach here is not to change catbox. Moving from cache to storage requires a very different api as most cases go beyond a super limited key-value pair. Also, the cache metadata overhead is wasteful in that case.
