### ISSUE TITLE
Ability to store cache item forever

### ISSUE THREAD

**Issue by dmyers** [hapijs/catbox#138]
With Redis and Memcache you can set the ttl value to `0`. I made an issue with `catbox-memory` to add support for it.

Does anyone know if the other engines would need to support it?

**Comment by jagoda** [comment]
I believe this same basic idea was brought up before in #123.

**Comment by hueniverse** [comment]
This module is explicitly designed to be a cache, not permanent storage. If you want to keep things forever, a simple access to the data storage would be better.
