### ISSUE TITLE
Can't drop method without arguments

### ISSUE THREAD

**Issue by KeKs0r** [hapijs/catbox#165]
Hi,
I am trying to drop a method that has no arguments.

If that is the case the id is an empty string. Which is not an issue for `policy.set`:

``` javascript
   const id = (key && typeof key === 'object') ? key.id : key;
    this._cache.set({ segment: this._segment, id: id }, value, ttl, (err) => {
```

https://github.com/hapijs/catbox/blob/master/lib/policy.js#L237-L238

But if I want to invalidate the same, I get an Error:

``` javascript
    const id = (key && typeof key === 'object') ? key.id : key;
    if (!id) {
        return callback(new Error('Invalid key'));
    }

    this._cache.drop({ segment: this._segment, id: id }, (err) => {
```

https://github.com/hapijs/catbox/blob/master/lib/policy.js#L257-L262

Is it possible to remove the id check?

**Comment by KeKs0r** [comment]
I found a workaround which solves it. Just generate a static key:

```javascript
        server.method('getCurrentGames', getCurrentGames, {
            bind: server,
            cache: {
                cache: 'redis',
                expiresIn: 1000 * 60 * 3,
                staleIn: 1000 * 60,
                staleTimeout: 10000,
                generateTimeout: 1000 * 5
            },
            generateKey: function (array) {
                return 'main';
            }
        });
```

I still think its not consistent, that set allows it, but not drop.

**Comment by tsuz** [comment]
Hi @hueniverse 

I couldn't find the contribution guide and made a PR for this bug. Let me know if it requires any more detail!
