### ISSUE TITLE
Can we remove the max() from staleIn?

### ISSUE THREAD

**Issue by EyePulp** [hapijs/catbox#166]
Looking here:
https://github.com/hapijs/catbox/blob/master/lib/policy.js#L282

`staleIn` has a max possible value of 1 ms less than a single day:
`staleIn: [Joi.number().integer().min(1).max(86400000 - 1), Joi.func()],`

Whereas `expiresIn` simply has a minimum:
`expiresIn: Joi.number().integer().min(1),`

Can we remove the max on `staleIn` or is it there for a reason?  I can make a PR if that's helpful, and I don't see any tests that are explicitly enforcing the behavior.

**Comment by legraphista** [comment]
+1
I can see the `staleIn` having to be lower than `expiresIn`, but I don't really understand the reason to limit it to 1 day

**Comment by EyePulp** [comment]
@legraphista One workaround to staleIn supports providing a function rather than a fixed integer, at which point you can return any value :

```javascript
//a convenience wrapper we use to create cache settings
// ms() is an npm module for defining readable millisecond counts
const cacheDefaults = function (settings,genKeyFn,expiresIn=ms('7 days'),staleIn=ms('1 day')){

    expiresIn  = settings.isdev?ms('2 min'):expiresIn;
    staleIn    = settings.isdev?ms('90 sec'):staleIn;

    const staleInFn=()=>staleIn;

    return {
        bind        : {settings:settings},
        generateKey : genKeyFn,
        cache       : {
            cache           : 'redisCache',
            generateTimeout : ms('60 sec'),
            expiresIn       : expiresIn,
            staleIn         : staleInFn,
            staleTimeout    : 100,
        },
    };
};
```

**Comment by hueniverse** [comment]
It's been like this since ever. Not sure why. I will review it one more time to make sure I am not forgetting something but doesn't look like we need this limit anymore.

**Comment by EyePulp** [comment]
Thanks @hueniverse =)

**Comment by hueniverse** [comment]
I knew there had to be a reason for that...
