### ISSUE TITLE
Can I use it with Amazon Elasticache ? How would I go about it ?

### ISSUE THREAD

**Issue by dvp0** [hapijs/catbox#171]

**Comment by mtharrison** [comment]
Last time I checked Elasticache is just Redis or Memcached so you can probably use out of the box either with https://github.com/hapijs/catbox-memcached or https://github.com/hapijs/catbox-redis depending which you choose.

**Comment by dvp0** [comment]
@mtharrison @hueniverse Thank you folks for super quick response !
