### ISSUE TITLE
Issues with pendingGenerateTimeout

### ISSUE THREAD

**Issue by kanongil** [hapijs/catbox#177]
The `pendingGenerateTimeout` option (from #152) doesn't work as advertised.

1. It doesn't work for non-stale responses.
1. It only attempts to prevent multiple generates in the current process.
1. If the cache expires while pending a generate, calling `get()` always trigger 503 / generateTimeout.
1. It can cause `get()` to __completely fail__ to respond (I have test to prove this).

…and more that I haven't fully investigated.

Given these, the feature really needs a total rewrite with a suitable test suite (currently, there is 1 functional test).

/cc @nathanmesserbbc

**Comment by nathanmesserbbc** [comment]
Hi Kanongil:

A few questions about your issues:

1. What non-stale responses do you mean? Do you mean while the value is being generated for the first time, or something else?

2. Yes, unless I've misunderstood something fundamental about catbox, everything (except the backend data store if not local memory) is local to the current process. All the protections in catbox for making excessive requests are just in the current process.

For 3. and 4. do you have tests you can share that show the problem?

**Comment by kanongil** [comment]
Regarding 4: This is actually caused by a catbox issue, fixed in #178. With the fix in place, we merely get an incorrect response.

**Comment by hueniverse** [comment]
This issue is not helpful. I need specific examples or failing tests to show the issues.
