### ISSUE TITLE
Suggestions or advice on a local disk storage adapter we've built

### ISSUE THREAD

**Issue by EyePulp** [hapijs/catbox#180]
Apologies if this is the wrong place to note this, but I'm not sure of a better location (maybe hapi/discuss)?

I built [catbox-disk](https://github.com/mirusresearch/catbox-disk) to provide a local cache that could be synched to other hapi servers in production or just shared across hapi instances on a single server.  It's relatively flat, portable, cheap and durable.

Basic aspects:
  - Stores everything in flat `.json` files with MD5 hashed filenames based off the keys to avoid encoding issues & length limits at the filesystem level.
  - we use initial hash character prefixes to split file storage into multiple sub directories to avoid excessive file counts in any one directory, e.g. `ABCD1234DEADBEEF.json` is stored in `.../AB/CD/ABCD1234DEADBEEF.json`
  - Cleanup routine with an adjustable interval to keep file growth in check for rarely accessed old files. 
  - Test coverage is 100%. 
  - Borrowed testing from other adapters to make sure we cover the right behaviors

I don't know if this would be of general use, but I'm more than happy to donate it or keep maintaining it under my org.  We're using it in production currently and watching closely for surprises. 

In our case we're using [Syncthing](https://syncthing.net/) separately to sync the files between multiple servers to have an eventually consistent shared cache.  Nothing related to the synchronization is part of the adapter itself.  The adapter just does R/W/D of `.json` files locally.

Suggestions or advice would be welcome.  Thanks!

**Comment by hueniverse** [comment]
Yep. hapijs/discuss.
