### ISSUE TITLE
Can't loop on keys that match a pattern.

### ISSUE THREAD

**Issue by acmoune** [hapijs/catbox#183]
It would be great if we could do this:

```javascript
server.cache.match(/regex-pattern/, (err, keys) => {
    keys.forEach((key) => {
        // Do stuffs with key, for example:
        server.cache.get(key, cb);
    });
});
```
Isn't it ?

**Comment by hueniverse** [comment]
Not possible. We don't keep a list of keys and not all providers can support it effectively.

**Comment by acmoune** [comment]
@hueniverse , thanks.

**Comment by acmoune** [comment]
@hueniverse, please can you give your advise on what brought me to create this request, [#501](https://github.com/hapijs/discuss/issues/501) ? I am still a newbie looking for good foundation.
