### ISSUE TITLE
The two year old example is broken

### ISSUE THREAD

**Issue by nlfiedler** [hapijs/catbox#195]
The `examples/policy.js` example code does not work.

**Comment by hueniverse** [comment]
There are nicer ways to say that the example needs to be updated...

**Comment by nlfiedler** [comment]
Sure, I was simply stating all that I knew about it. I couldn't tell what was wrong, but it seemed that maybe the API changed? That was as much information as I had.

**Comment by hueniverse** [comment]
I was referring to the "The two year old" part. It comes off somewhat hostile.
