### ISSUE TITLE
Default memory caching is not promise safe

### ISSUE THREAD

**Issue by holmok** [hapijs/catbox#207]
When using `require('make-promises-safe')` the default memory caching kills the application.  Here is some sample code...

```javascript
// require('make-promises-safe')
const Hapi = require('hapi')

const server = Hapi.server({
  host: 'localhost',
  port: 8000
})

server.route({
  method: 'GET',
  path: '/',
  async handler (request, h) {
    const now = await request.server.methods.date()
    return `hello world it is ${now}`
  }
})

server.method(
  'date', 
  () => new Date().toISOString(), 
  { cache: { expiresIn: 2000, generateTimeout: 100 } }
)

async function start () {
  try {
    await server.start()
  } catch (err) {
    console.log(err)
    process.exit(1)
  }
  console.log('Server running at:', server.info.uri)
};

start()
```

This code works fine with `// require('make-promises-safe')` commented out, but as soon as you uncomment it and call to `const now = await request.server.methods.date()` in a handler the process ends and outputs this to the console. 

```resolve Promise { '2018-11-18T16:50:31.617Z' } undefined```

**Comment by devinivy** [comment]
I tested this out and can confirm.  It seems to be due to [`multipleResolves`](https://nodejs.org/dist/latest-v10.x/docs/api/process.html#process_event_multipleresolves).  Going to continue and take a closer look.

**Comment by devinivy** [comment]
The promise that is resolving twice is the `Promise.race()` found [here](https://github.com/hapijs/catbox/blob/master/lib/policy.js#L161-L164).  Related to a potential V8 quirk mentioned in this issue https://github.com/nodejs/node/issues/24321.

**Comment by kanongil** [comment]
This is all rather quite silly. Now, if I want to make a deferred, where I intend to support multiple resolves / rejects, I need to keep track of the state of the promise (replicating the internal state).

**Comment by devinivy** [comment]
I believe this is resolved (😉) in make-promises-safe v4.

**Comment by holmok** [comment]
👍 thanks.
