### ISSUE TITLE
If generate takes longer than staleTimeout, errors get swallowed

### ISSUE THREAD

**Issue by jgallen23** [hapijs/catbox#210]
We have a method that gets data from a 3rd party api and we are ok with it returning stale data most of the time, so we set the `staleTimeout` to 1 and the `staleIn` to 3 hours and `expiresIn` to 10 days and `dropOnError` to false.  Inside our method, we just make a call to the 3rd party api and let it throw if it fails.  The problem is that because the `staleTimeout` is always less than the request time, any errors that happen inside the method get completely swallowed and we don't get any visibility until the `expiresIn` passes and then our service stops serving stale data and goes down.

Do others run into this issue?  Is it worth submitting a PR? (My last one is still sitting there, so I'm not sure if you'd be open to it)

**Comment by hueniverse** [comment]
@kanongil any comment?

**Comment by jgallen23** [comment]
thanks @hueniverse
